### ISSUE TITLE
Cleaning up history

### ISSUE THREAD

**Issue by andrewshadura** [syncthing-gtk/syncthing-gtk#10]
I’m working on reconciling changes from all forks in the branch [`next`](https://github.com/syncthing-gtk/syncthing-gtk/tree/next). I’m not including the stignore integration for Nautilus, as that requires a bit more of attention and work, in my opinion.

I also have a branch where I worked on some GTK issues. It was based on an old fork of mine, so after a rebase I had to solve some conflicts, but I think I’m mostly done (see `wip/next/gtk-fixes`).

I have a question about commit fe1bf73eae63: @Rudd-O, could you please expand on why that is necessary? I tried to understand why that was happening, and the commit message was not enough. It’s be best if you wrote it in a format of a commit message, so that I could use it in a cherry-pick from the current `master`.

**Comment by Salamandar** [comment]
Once we re-fork the repository from kozec's repo, we can do new pull requests and maybe have a nicer history.

**Comment by Rudd-O** [comment]
On commit fe1bf73 it was necessary to merge the incoming values into the preexisting cons[self my id].  Without this, you'd get incessant errors on stderr and the program would just not work.

Once you are content with the reconciliation in next branch, please stick to the guideline of sending small PRs to merge these changes, rather than a giant one with all changes at once.

**Comment by andrewshadura** [comment]
I'm curious if the underlying cause is elsewhere, because I never encountered those in my fork.

**Comment by Rudd-O** [comment]
I vaguely remember that the API changed and started sending totals in addition to per-connection data in the same data structure, and this is what I discovered using printf debugging.  You can try with a recent syncthing, see if you find the problem again – I am pretty sure you'll hit it.  Either way, this does work today.

**Comment by andrewshadura** [comment]
Right, I guess the old Syncthing is the reason I don’t see it (Debian still has 1.12.1).

**Comment by Rudd-O** [comment]
Wew lad.  Time to get a nice VBox with Fedora 36 running ;-)

**Comment by hrehfeld** [comment]
> I’m not including the stignore integration for Nautilus, as that requires a bit more of attention and work, in my opinion.

With zero knowledge about how that mechanism is implemented: Does it make sense to put that into a separate repo? (A simple no is an acceptable answer ;-))

**Comment by andrewshadura** [comment]
> > I’m not including the stignore integration for Nautilus, as that requires a bit more of attention and work, in my opinion.
> 
> With zero knowledge about how that mechanism is implemented: Does it make sense to put that into a separate repo? (A simple no is an acceptable answer ;-))

I don’t think it would make sense to make it separate. Also, the stignore parser may be useful later in the GUI itself.

**Comment by Salamandar** [comment]
I think we can close that, right ?
