### ISSUE TITLE
Building the latest git tag fails

### ISSUE THREAD

**Issue by es20490446e** [syncthing-gtk/syncthing-gtk#15]
If you try to build the latest tag from git, it will fail complaining that "python3" is an invalid version.

**Comment by Salamandar** [comment]
This should be fixed. This was due to a crappy legacy setup.py. It's fixed, until we just replace this setup.py with something better.

**Comment by es20490446e** [comment]
Now the app no longer works:
https://github.com/syncthing-gtk/syncthing-gtk/issues/19

**Comment by Rudd-O** [comment]
I had a fix for this in my fork.
