### ISSUE TITLE
Tags are gone

### ISSUE THREAD

**Issue by es20490446e** [syncthing-gtk/syncthing-gtk#17]
There are no longer tags, or any kind of versioning, in this repo.

Meaning I'm currently unable to package it.

**Comment by Rudd-O** [comment]
The tags should be migrated by pushing `--tags` from the old copy of the repo to here.  @Salamandar please?

**Comment by Salamandar** [comment]
Yeah :'( sorry for the inconvenience… Tags have been pushed. The AUR package `syncthing-gtk` is now working again.

**Comment by es20490446e** [comment]
Thanks 👌

Now there's a second problem: some tags start with "v", where one doesn't.

So in the package recipe I can't just write down the source URL, because I don't know if it is going to have that "v" or not.

Maybe removing "v" in all tags is the best solution.

**Comment by Salamandar** [comment]
Yes I'm actually working on it. You mean for the -git package ?

**Comment by es20490446e** [comment]
I have my own repo, with its own package.

But I guess everyone will encounter the same problem

**Comment by Salamandar** [comment]
This is fixed.

There was also an issue due to setuptools.versionning dropping support for legacy version numbers. This is fixed too.

**Comment by es20490446e** [comment]
Previously there were tags for 0.9.4.5 and 0.9.4.6, but not now.

Is that correct?

**Comment by Salamandar** [comment]
Yes, it is. Those tags were on another branch due to 2 repositories being merged.

**Comment by es20490446e** [comment]
Oki, thanks for the fix. Have a nice day!  👌😉
