### ISSUE TITLE
Crashes: tools.py: Inconsistent use of tabs and spaces

### ISSUE THREAD

**Issue by es20490446e** [syncthing-gtk/syncthing-gtk#19]
syncthing-gtk is currently broken.

Compiling the latest tag:
https://github.com/syncthing-gtk/syncthing-gtk/releases/tag/0.9.4.4

Then launching the app results in:

```
Traceback (most recent call last):
  File "/usr/bin/syncthing-gtk", line 21, in <module>
    from syncthing_gtk.tools import init_logging, init_locale
  File "/usr/lib/python3.10/site-packages/syncthing_gtk/tools.py", line 373
    from gi.repository import GLib
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by Salamandar** [comment]
You should know we're in the process of ressuscitating an abandonware, so there might be things like that that break until everything is sorted out.

**Comment by es20490446e** [comment]
Thanks for resurrecting this application.

A while ago I was considering doing something myself about it, but I chose to postpone it due to more pressing applications not working.

The alternatives to this seem in worse status. For example qsyncthingtray leaks memory and it is abandoned.

**Comment by Rudd-O** [comment]
A recently-approved PR solves the tabs vs spaces problem.  It's going in!

**Comment by es20490446e** [comment]
Oh where? :octocat:

**Comment by Salamandar** [comment]
> Thanks for resurrecting this application.
> 
> A while ago I was considering doing something myself about it, but I chose to postpone it due to more pressing applications not working.
> 
> The alternatives to this seem in worse status. For example qsyncthingtray leaks memory and it is abandoned.

Well feel free to come help here ! ;)

For now we're working on having a stable python3 port. Then maybe GTK4. Also, i didn't discuss it with the others, but maybe changing the language used ? (Rust ?) That might reduce the energy it consumes for mobile applications.

**Comment by Salamandar** [comment]
> Oh where? :octocat:

#18

**Comment by Rudd-O** [comment]
If we have verified this is no longer an issue, can we close this issue?

**Comment by Salamandar** [comment]
I haven't checked 😁 i should do it today or tomorrow.

**Comment by es20490446e** [comment]
> Maybe changing the language used ? (Rust ?) That might reduce the energy it consumes for mobile applications.

It won't, because Python is acting just as glue language.

The real computation is made on the syncthing daemon, which is already written in a high performance language.

The user interface just calls GTK, which is the same.

Python is easier to develop than Rust. It only makes sense going for a more complex, more performant, language when there's substantial CPU computation.

If the language is just gluing other components, or just working with IO, it doesn't matter. It will matter more the ease of development.


---
> For now we're working on having a stable python3 port. Then maybe GTK4.

If this was me I would first consider which features are worth removing all together, because in synthing-gtk there are many things that were useful once upon a time, but in the modern world I have doubts about it.

A few examples:

- **Manual rate limit**: A decade ago routers were unable to handle many streams of data gracefully, hence background apps developed manual rate limiting. But this is no longer the case, modern routers are greatly overprovisioned, and can make background streams not to affect foreground ones, using for example [Wireless Multimedia Extensions](https://en.wikipedia.org/wiki/Wireless_Multimedia_Extensions).

- **GTK interface**: These days the web interface does everything better than the GTK interface, being some defaults for new added folders more intuitive for a non so experienced users. Hence probably having both interfaces does nothing.

- **Daemon priority**: The syncthing daemon used to launch with normal priority, but these days it changes itself to be low priority by default. Hence being able to set the daemon priority does nothing, and actually it is broken because "normal priority" automatically changes to "low priority".

- **Selecting when to launch the daemon**: It can be figured out automatically. If the daemon is off upon launch, you start it and close it when exiting syncthing-gtk. If it is already on, you do nothing.

I would argue that the only relevant features of syncthing-gtk is just showing a tray icon, being able to launch the web interface, and start the daemon if it is off. And the rest are potential candidates for removal.

Maybe ask some people if they are using other features and how. It may save time afterwards.


---
> Well feel free to come help here ! ;)

Currently I'm development an intricate libre software. When that's good enough, I will consider.

Also, even when I code nicely, I feel that my best contributions are rarely on coding alone, but on improving the design of software.

But in my experience, on collaborative efforts, people are rarely open to modify design.

For example in one instance I approached Kwin developers, and I suggested that any full-screen app will disable desktop effects by default, hence that app will have better performance.

As usual they didn't see the value of that. Then I decided to code a plugin for that, called [Autocomposer](https://www.pling.com/p/1502826), that did such thing.

Quickly it became one of the most downloaded plugin for the KDE Plasma desktop. It has 14 reviews, and each single one rates the plugin as 10.

It happens like that most of the time. When I try to collaborate with other people they end rejecting almost everything I suggest, and I end coding a better alternative all by myself.


---
> Can we close this issue?

Is it possible to build the latest version, either from master or tags?

Or shall we just give up on building for the moment being?

**Comment by Rudd-O** [comment]
> If this was me I would first consider which features are worth removing all together, because in synthing-gtk there are many things that were useful once upon a time, but in the modern world I have doubts about it.
> A few examples:
> 
>     * **Manual rate limit**: A decade ago routers were unable to handle many streams of data gracefully, hence background apps developed manual rate limiting. But this is no longer the case, modern routers are greatly overprovisioned, and can make background streams not to affect foreground ones, using for example [Wireless Multimedia Extensions](https://en.wikipedia.org/wiki/Wireless_Multimedia_Extensions).

This is not a Syncthing-GTK feature — it is a Syncthing feature.  This app merely reconfigures Syncthing to have a data rate limit.

> 
>     * **GTK interface**: These days the web interface does everything better than the GTK interface, being some defaults for new added folders more intuitive for a non so experienced users. Hence probably having both interfaces does nothing.

The entire reason this app exists is *as a replacement for the Web interface*.  Some of us don't want to run the Web interface, don't want to have the additional HTTP port listening unprotected on `localhost`, or prefer a *native* application instead of a *Web* application.

>     * **Daemon priority**: The syncthing daemon used to launch with normal priority, but these days it changes itself to be low priority by default. Hence being able to set the daemon priority does nothing, and actually it is broken because "normal priority" automatically changes to "low priority".

This is a reasonable ask.  Not having to maintain this priority setting would cut the amount of code slightly.

>     * **Selecting when to launch the daemon**: It can be figured out automatically. If the daemon is off upon launch, you start it and close it when exiting syncthing-gtk. If it is already on, you do nothing.

This is a reasonable observation.  In modern distros, Syncthing should basically be started / stopped using the systemd user unit that the distribution ships (and we should too).  Syncthing-GTK would not actually be running at the appropriate times to make this decision effective anyway.

> I would argue that the only relevant features of syncthing-gtk is just showing a tray icon, being able to launch the web interface, and start the daemon if it is off. And the rest are potential candidates for removal.

You're suggesting we scrap the entire app.  Those of us using the app do so *precisely because we don't want to use the Web interface*.

**NAK**.

**Comment by Rudd-O** [comment]
> For example in one instance I approached Kwin developers, and I suggested that any full-screen app will disable desktop effects by default, hence that app will have better performance.

OT, but AFAIK KWin already disables window redirect when fullscreen (you can clearly see a flicker when it is reenabled after existing fullscreen), and disabling redirect is what gains you the performance (no need to disable the effects, which anyway are not doing anything when fullscreen), so I can see why the KWin people said "meh, not something we want to maintain long-term".

**Comment by es20490446e** [comment]
> Some of us don't want to run the Web interface, don't want to have the additional HTTP port listening unprotected on `localhost`, or prefer a _native_ application instead of a _Web_ application.

I see.


> In modern distros, Syncthing should basically be started / stopped using the systemd user unit that the distribution ships (and we should too).

Anyways it's kind of convenient that syncthing-gtk starts the syncthing unit by itself. Because it can provide an graphical interface to toggle that, and different users can select if to enable it or not.

The interface could only offer to start the syncthing-gtk at the beginning of the user session. Since that unit depends on syncthing, that second one is started anyway.

Also the graphical interface should not differentiate between unit or not unit, just figure out if the particular system uses systemd units or `~/.config/autostart`.

Probably disabling the syncthing-gtk unit should also disable the syncthing one.


> AFAIK KWin already disables window redirect when fullscreen (you can clearly see a flicker when it is reenabled after existing fullscreen)

I don't think it works like that.

Kwin has an option to allow applications to block compositing, because compositing on X is always taking resources.

X doesn't have a notion of what is seen or unseen, it needs to render everything. For instance it needs to render every single tab in your browser, even if it is covered by a full-screen application.

The thing is that applications shall explicitly request that block. Bust most full-screen applications don't do so, even when it doesn't make any benefit having composition, simply because the hole desktop is covered by a window.

The main reason that Kwin developers didn't want to implement that was simply because they are concentrating their efforts into Wayland.

But the thing is Wayland may be viable or not, or may take a long time. Right now for gaming is a no no, works slower and with greater latency.

**Comment by es20490446e** [comment]
> Some of us don't want to run the Web interface, don't want to have the additional HTTP port listening unprotected on `localhost`

I suspect this is also no longer true. The web interface ask you to password protect it on first launch, and I suspect it is enabled by default anyways when you start the daemon.

> Or prefer a _native_ application instead of a _Web_ application.

In this particular situation I don't personally see the advantage of that.

Also the default settings on the native application when adding a folder doesn't seem good ones.

**Comment by Salamandar** [comment]
> It won't, because Python is acting just as glue language.

Can't disagree more. We can see Rust-based GTK wrapper for a lot of tools. Pika-Backup is the first that pops into my mind. Yes, it is a glue language, but this glue language has the work to transfer signals, launch GTK, make network requests, etc. and that's not "nothing".

**Comment by es20490446e** [comment]
- How much CPU usage is syncthing-gtk using when transferring files?

- Does Pika-Backup delegate computation to a daemon?

- Does transferring signals, launching GTK, and making network requests consume more resources depending on the programming language?

**Comment by Salamandar** [comment]
> * How much CPU usage is syncthing-gtk using when transferring files?

It's not about cpu usage. It's about cpu interrupts and wake-ups. Filesystem access. It's all about power savings. Python is bad at that.

> * Does Pika-Backup delegate computation to a daemon?

Yes, it's basically the same structure as Syncthing-gtk : It uses Borg under the hood, and is basically "just" a configuration UI.

> * Does transferring signals, launching GTK, and making network requests consume more resources depending on the programming language?

Yes, it does. Just run syncthing-gtk via strace and you'll see. I love python, I really do, but you can't deny it's not the most efficient language out there. And once again, it's not about CPU usage but about power savings (here I was talking about using Rust for a potential mobile app).

**Comment by Rudd-O** [comment]
> In this particular situation I don't personally see the advantage of that.

Then you're not the target audience for the app.

**Comment by Rudd-O** [comment]
> Python is bad at that.

Python will not wake your CPU unless you have a timer somewhere in your code.  It's not efficient when it's running, but we can expect an app like Syncthing-GTK to consume less than 1% CPU when it's doing something, and probably 0% if doing nothing at all*.

\* not entirely the case since it receives data from the daemon.  this data polling should be suspended when the user has the app minimized / icontray'd, precisely to save battery.  this would go even if the app was written in Rust.

**Comment by Salamandar** [comment]
Let's close this :)
