### ISSUE TITLE
Feature: Do not require tray icon for the program to work in the background

### ISSUE THREAD

**Issue by alduraibi** [syncthing-gtk/syncthing-gtk#35]
With Gnome introducing "Background Apps", it would be great if the program would be able to work and run in the background without the need of a tray icon.

Also, some options are only accessible through the tray icon and not through the main window menu which would need to be included in order to not rely on the tray icon. The missing options are: `Preferences`, `Open Web Interface`, `See Logs`, `About` and `Quit`.

**Comment by Salamandar** [comment]
> Also, some options are only accessible through the tray icon and not through the main window menu which would need to be included in order to not rely on the tray icon. The missing options are: Preferences, Open Web Interface, See Logs, About and Quit.

They are actually available but indeed, the app menu should be revamped.

> With Gnome introducing "Background Apps", it would be great if the program would be able to work and run in the background without the need of a tray icon.

You can run syncthing without syncthing-gtk. I don't know how those "background apps" are implemented in Gnome, but yeah we could plug into it.
