### ISSUE TITLE
No .exe Windows installer in release

### ISSUE THREAD

**Issue by lil5** [syncthing-gtk/syncthing-gtk#59]
I realize this is a comparatively new fork but a Windows version would be appreciated

**Comment by realAllonZ** [comment]
The README.md says "On Windows Get the installer [here](https://github.com/syncthing-gtk/syncthing-gtk/releases/latest)" but there is no installer there. Any timeline on the .exe?

**Comment by lil5** [comment]
@realAllonZ
For those looking for windows support: https://github.com/canton7/SyncTrayzor

**Comment by realAllonZ** [comment]
The README still needs updated to reflect that there is no windows installation.

SyncTrayzor has not released a commit for about 2.5 years and besides that it is way too buggy.
